import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/theme-provider";
import { Sidebar } from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="antialiased"
    >
      <body className={inter.className}>
        <ThemeProvider
          forcedTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen lg:grid lg:grid-teste dark:bg-zinc-900">
            <Sidebar />
            <main className="px-4 p-12 pt-24 lg:col-start-2 lg:px-8 pb-12 lg:pt-8 max-w-screen">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
